mysql_resource_name = "mysql-docker-80"
binlog_index_file = "~/mysql-data/mysql-80/binlog.index"
resume_offset_file = "~/mysql-cdc/producer.offset"
local_store_file = "~/mysql-cdc/producer.store"

[filters]
include_dbs = [ "flvTest" ]

[fluvio]
topic = "rust-mysql-cdc"
replicas = 2