##
# CDC Consumer Profile
##

##
# Data Path (mysql container mapped to local drive)
#
# last_offset_file: consumer resumes from here after restart
#
##
[data]
base_path = "~/mysql-cdc/mysql-consumer"
last_offset_file = "consumer.offset"

##
# Mysql database settings
##
[database]
ip_or_host = "0.0.0.0"
port = 3090
user = "fluvio"
password ="fluvio4cdc!"

##
# Container configuration (used by ./docker scripts)
##
[container]
name = "mysql-consumer"
host_port = 3090

##
# Filters to include or exclude databases
##
[filters]
include_dbs = ["flvDb"]

##
# Fluvio streaming settings
##
[fluvio]
topic ="rust-mysql-cdc"